### PR TITLE
fix for img with src that link to a svg file

### LINKED ISSUE #8: Working with SVG
Hi :)

I tryed to inline some svg icons here : https://github.com/Shuunen/folio/tree/feat/inline-svg-via-parcel-plugin-inliner

But it produce weird base 64, here is the before after build : 

image

Any ideas ?

### PR DESCRIPTION
**Pull request by Shuunen**
fix shff/parcel-plugin-inliner/issues/8

### CODE REVIEW

**Comment by shff** [comment]
Hmmm, this looks like a problem with https://github.com/sindresorhus/file-type . They even mention it in the README, but he already refused to change it in two issues.

I think this is something we can fix in `posthtml-inline-assets` so other users of this package can take advantage of it!

I'll try opening a PR there, if takes too long, I'll publish an alternative package :)

**Comment by shff** [comment]
Opened a PR @ jonathantneal/posthtml-inline-assets#13

**Comment by Shuunen** [comment]
nice 😄 last commit on `posthtml-inline-assets` is from Nov 6, 2018, let's hope it's still active

**Comment by shff** [comment]
Hi @Shuunen!

I just published a temporary package in a personal scope in the meanwhile: https://www.npmjs.com/package/@shferreira/posthtml-inline-assets

I also published an "alpha" version of parcel-plugin-inliner that uses the package above right here: https://www.npmjs.com/package/parcel-plugin-inliner/v/1.0.10 .

You can install it with:

```bash
npm install parcel-plugin-inliner@1.0.10
```

Or:

```bash
yarn add parcel-plugin-inliner@1.0.10
```

**Comment by shff** [comment]
Repeating what I mentioned at #8 

> I removed the alpha tag from version 1.0.10 and marked it as latest. Since my release of posthtml-inline-assets is and will be kept up to date with the original repo, I don't think there's a problem to use it for now. The code is pure Javascript and is 100% verifiable.
> 
> I'll use the original dependency as soon as my PR is merged to posthtml-inline-assets, or when the owner of the package can find some other way to fix SVG handling.
> 
> Thanks a lot for finding the bug and making code to solve it, Shuunen :)

**Pull request closed without merging**
